apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{"notifications.argoproj.io/subscriptions":"-
      trigger: [on-analysis-run-error, on-analysis-run-failed,
      on-analysis-run-running, on-rollout-aborted, on-rollout-completed,
      on-rollout-paused, on-rollout-step-completed, on-rollout-updated,
      on-scaling-replica-set]\n  destinations:\n    - service: slack\n     
      recipients:
      [davey-jones-locker]\n"},"labels":{"app.kubernetes.io/instance":"test1","name":"meeech-old-timey-service-1"},"name":"scratch-meeech-old-timey-service","namespace":"testns1"},"spec":{"replicas":3,"revisionHistoryLimit":10,"rollbackWindow":{"revisions":5},"selector":{"matchLabels":{"app.kubernetes.io/instance":"scratch","app.kubernetes.io/name":"meeech-old-timey-service"}},"strategy":{"canary":{"canaryMetadata":{"labels":{"release-stage":"canary","service-role":"live"}},"canaryService":"scratch-meeech-old-timey-service-canary","stableMetadata":{"labels":{"release-stage":"stable","service-role":"live"}},"steps":[{"setWeight":25},{"pause":{"duration":"15m"}},{"setWeight":50},{"pause":{"duration":"20m"}},{"setWeight":100},{"pause":{"duration":"10m"}}]}},"template":{"metadata":{"annotations":{"randomToForceNewRS":"5md2V"},"labels":{"app.kubernetes.io/component":"service","app.kubernetes.io/instance":"scratch","app.kubernetes.io/name":"meeech-old-timey-service","name":"meeech-old-timey-service-1","service-role":"live","tags.datadoghq.com/env":"local","tags.datadoghq.com/service":"meeech-old-timey-service","tags.datadoghq.com/version":"1.0.0"}},"spec":{"containers":[{"env":[{"name":"HTTP_PORT","value":"8080"},{"name":"K8S_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"K8S_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"K8S_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"ghcr.io/argocon22workshop/rollouts-demo:yellow","imagePullPolicy":"IfNotPresent","name":"meeech-old-timey-service","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"limits":{"memory":"30Mi"},"requests":{"memory":"8Mi"}},"securityContext":{},"volumeMounts":[{"mountPath":"/etc/podinfo","name":"podinfo"}]}],"securityContext":{},"serviceAccountName":"scratch-meeech-old-timey-service","volumes":[{"downwardAPI":{"items":[{"fieldRef":{"fieldPath":"metadata.labels['release-stage']"},"path":"release-stage"}]},"name":"podinfo"}]}}}}
    notifications.argoproj.io/subscriptions: >
      - trigger: [on-analysis-run-error, on-analysis-run-failed,
      on-analysis-run-running, on-rollout-aborted, on-rollout-completed,
      on-rollout-paused, on-rollout-step-completed, on-rollout-updated,
      on-scaling-replica-set]
        destinations:
          - service: slack
            recipients: [davey-jones-locker]
    rollout.argoproj.io/revision: '3'
  creationTimestamp: '2024-02-07T00:15:21Z'
  generation: 3
  labels:
    app.kubernetes.io/instance: test1
    name: meeech-old-timey-service-1
  name: scratch-meeech-old-timey-service
  namespace: testns1
  resourceVersion: '196116'
  uid: df8c0c88-3e2b-4c1c-873d-f98388dad666
spec:
  replicas: 3
  revisionHistoryLimit: 10
  rollbackWindow:
    revisions: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: scratch
      app.kubernetes.io/name: meeech-old-timey-service
  strategy:
    canary:
      canaryMetadata:
        labels:
          release-stage: canary
          service-role: live
      canaryService: scratch-meeech-old-timey-service-canary
      stableMetadata:
        labels:
          release-stage: stable
          service-role: live
      steps:
        - setWeight: 25
        - pause:
            duration: 15m
        - setWeight: 50
        - pause:
            duration: 20m
        - setWeight: 100
        - pause:
            duration: 10m
  template:
    metadata:
      annotations:
        randomToForceNewRS: '12'
      labels:
        app.kubernetes.io/component: service
        app.kubernetes.io/instance: scratch
        app.kubernetes.io/name: meeech-old-timey-service
        name: meeech-old-timey-service-1
        service-role: live
        tags.datadoghq.com/env: local
        tags.datadoghq.com/service: meeech-old-timey-service
        tags.datadoghq.com/version: 1.0.0
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: '8080'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: 'ghcr.io/argocon22workshop/rollouts-demo:yellow'
          imagePullPolicy: IfNotPresent
          name: meeech-old-timey-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 30Mi
            requests:
              memory: 8Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      securityContext: {}
      serviceAccountName: scratch-meeech-old-timey-service
      volumes:
        - downwardAPI:
            items:
              - fieldRef:
                  fieldPath: 'metadata.labels[''release-stage'']'
                path: release-stage
          name: podinfo
status:
  HPAReplicas: 4
  availableReplicas: 4
  blueGreen: {}
  canary: {}
  conditions:
    - lastTransitionTime: '2024-02-07T00:15:22Z'
      lastUpdateTime: '2024-02-07T00:15:22Z'
      message: Rollout has minimum availability
      reason: AvailableReason
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-02-07T00:15:43Z'
      lastUpdateTime: '2024-02-07T00:15:43Z'
      message: Rollout is not healthy
      reason: RolloutHealthy
      status: 'False'
      type: Healthy
    - lastTransitionTime: '2024-02-07T00:15:43Z'
      lastUpdateTime: '2024-02-07T00:15:43Z'
      message: RolloutCompleted
      reason: RolloutCompleted
      status: 'False'
      type: Completed
    - lastTransitionTime: '2024-02-07T00:15:51Z'
      lastUpdateTime: '2024-02-07T00:15:51Z'
      message: Rollout "scratch-meeech-old-timey-service" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-02-07T00:15:51Z'
      lastUpdateTime: '2024-02-07T00:15:51Z'
      message: Rollout is paused
      reason: RolloutPaused
      status: 'False'
      type: Paused
  currentPodHash: 66b8bbdd6c
  currentStepHash: 86c5f95ccd
  currentStepIndex: 0
  message: more replicas need to be updated
  observedGeneration: '3'
  phase: Progressing
  readyReplicas: 4
  replicas: 4
  selector: >-
    app.kubernetes.io/instance=scratch,app.kubernetes.io/name=meeech-old-timey-service
  stableRS: 65c7c4c5d4

