apiVersion: v1
kind: Service
metadata:
  annotations:
    argo-rollouts.argoproj.io/managed-by-rollouts: scratch-meeech-old-timey-service
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"test1","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"meeech-old-timey-service","app.kubernetes.io/version":"1.0.0","helm.sh/chart":"meeech-old-timey-service-1.0.0","kong_upstream":"meeech-old-timey-service","kube_app_name":"meeech-old-timey-service"},"name":"scratch-meeech-old-timey-service-canary","namespace":"testns1"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"scratch","app.kubernetes.io/name":"meeech-old-timey-service"},"type":"ClusterIP"}}
  creationTimestamp: '2024-02-06T00:22:42Z'
  labels:
    app.kubernetes.io/instance: test1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: meeech-old-timey-service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: meeech-old-timey-service-1.0.0
    kong_upstream: meeech-old-timey-service
    kube_app_name: meeech-old-timey-service
  name: scratch-meeech-old-timey-service-canary
  namespace: testns1
  resourceVersion: '196090'
  uid: 5c62aa4d-725a-43ed-9bc6-2fbe65684da2
spec:
  clusterIP: 10.43.84.67
  clusterIPs:
    - 10.43.84.67
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: scratch
    app.kubernetes.io/name: meeech-old-timey-service
    rollouts-pod-template-hash: fb6f59765
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

